name: cityCom

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash


      - name: Generate deployment package
        run: |
          mkdir -p city-deploy
          cp scripts/*.sh ./city-deploy
          cp appspec.yml ./city-deploy
          cp build/libs/*.jar ./city-deploy
        shell: bash

      - name: Make zip file
        run: zip -r ./deploy.zip ./city-deploy
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_CTCOM_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_CTCOM_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./deploy.zip s3://ctcom-build/deploy.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name ctcom --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name ctcom-group --s3-location bucket=ctcom-build,bundleType=zip,key=deploy.zip
